### ISSUE TITLE
Calculate Accessibility Matrix - TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by MatthewLehane** [Esri/public-transit-tools#168]
Having issues running the Calculate Accessibility Matrix tool - Have a transit enabled network dataset I created a while ago and am completing some preliminary testing to understand the tool outputs for future automation in Python. 

Ran into the error below - any idea on fixes? I assume the transit analysis tools are still supported? 

`Start Time: Thursday, September 22, 2022 6:21:59 PM
Validating OD Cost Matrix settings...
Inputs successfully validated.
Copying origins to output...
Deleting pre-existing output fields...
Traceback (most recent call last):
  File "<string>", line 900, in execute
  File "D:\GISData\Projects\TransitRouting\tools\TransitNetworkAnalysisTools_0.7.0\CalculateODMatrixInParallel.py", line 438, in solve_large_od_cost_matrix
    self._execute_solve()
  File "D:\GISData\Projects\TransitRouting\tools\TransitNetworkAnalysisTools_0.7.0\CalculateODMatrixInParallel.py", line 612, in _execute_solve
    super()._execute_solve()
  File "D:\GISData\Projects\TransitRouting\tools\TransitNetworkAnalysisTools_0.7.0\CalculateODMatrixInParallel.py", line 375, in _execute_solve
    with subprocess.Popen(
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\subprocess.py", line 1360, in _execute_child
    args = list2cmdline(args)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\subprocess.py", line 565, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
Failed to execute (CalculateAccessibilityMatrix).
Failed at Thursday, September 22, 2022 6:22:01 PM (Elapsed Time: 2.45 seconds)`

**Comment by mmorang** [comment]
I think this error has already been fixed in the latest version of the code.  It looks like you're running 0.7.0, and 0.7.1 is now available at https://www.arcgis.com/home/item.html?id=23cc1b720eb0418db4d0e61955b8fe43.  Please give that a try and let me know if you're still having the problem.

**Comment by MatthewLehane** [comment]
Worked now - thank you!
